spring.application.name=cpn-backend

server.port=${PORT:8080}

# MySQL Database Config (env vars for production, fallback to local XAMPP for dev)
spring.datasource.url=jdbc:mysql://gondola.proxy.rlwy.net:41623/railway?useSSL=true&requireSSL=true
spring.datasource.username=root
spring.datasource.password=YUOHpHDajJQHHeRmNUFfEZqvveLnyvvd
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hibernate (update ensures existing data isn't completely dropped every time)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mvc.dispatch-options-request=true