spring.application.name=cpn-backend

server.port=8080

# MySQL Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/cpndb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hibernate (update ensures existing data isn't completely dropped every time)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
